// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk091935377/appengine/go_appengine/goroot-1.8`
const TheVersion = `1.8.7 (appengine-1.9.71)`
const Goexperiment = ``
const StackGuardMultiplier = 1

